name: Deploy to Vercel
on: [push]
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- uses: vercel/action@v1
with:
vercel-token: ${{ secrets.VERCEL_TOKEN }}
alias: 'your-custom-domain.com'
always-link-latest: false
